<a href="https://colab.research.google.com/github/AchmadRaihan/MachineLearningCourses/blob/main/Week%209/linear_regression_concise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install d2l

# Concise Implementation of Linear Regression

In [ ]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

In [ ]:
true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

## Reading the Dataset


In [ ]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

In [ ]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [ ]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[-1.8662441 , -0.76892567],
        [ 0.67929685,  0.9496371 ],
        [ 0.2291939 ,  0.70081353],
        [-0.7775966 , -0.14535384],
        [-1.0970132 , -1.8890083 ],
        [ 0.6007258 ,  1.4242705 ],
        [ 0.64704937,  1.0289823 ],
        [-0.58734983, -0.5709556 ],
        [-0.93384165, -1.4953911 ],
        [ 0.04729045,  1.5638678 ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 3.0722752 ],
        [ 2.3232365 ],
        [ 2.2942677 ],
        [ 3.1392274 ],
        [ 8.4219675 ],
        [ 0.57171255],
        [ 1.9876167 ],
        [ 4.9669294 ],
        [ 7.412868  ],
        [-1.0243363 ]], dtype=float32)>)

## Defining the Model



In [ ]:
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

## Initializing Model Parameters

In [ ]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

## Defining the Loss Function


In [ ]:
loss = tf.keras.losses.MeanSquaredError()

## Defining the Optimization Algorithm


In [ ]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

## Training

In [ ]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000302
epoch 2, loss 0.000101
epoch 3, loss 0.000100


In [ ]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([-0.00012922  0.00013113], shape=(2,), dtype=float32)
error in estimating b [-0.00024366]
